add netlify reactions post
PaulieScanlon/paulie-dev-2019 pull request #2
Opened 2020-07-09 21:51 UTC by PaulieScanlon

2020-07-10 03:34 UTC, jlengstorf requested changes
looking good! I made some edits and a few suggestions. let me know if you have questions!

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +... and feel free to come find me on Twitter, [@pauliescanlon](https://twitter.com/PaulieScanlon)
on the Netlify blog post, this is probably a little too much self-promo. typically I throw a "let’s discuss this on Twitter" into the footer of a blog post so there's _some_ promo, but not so much that it distracts from the rest of the post

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +You're probably familiar with reactions from social media platforms such as Twitter, Instagram et al but i rarely see reactions used in Blog posts. The more common approach in blog posts is to use a
```suggestion
You're probably familiar with reactions from social media platforms such as Twitter, Instagram et al., but I rarely see reactions in blog posts. A common approach in blogs is to [implement comments](https://css-tricks.com/roll-your-own-comments-with-gatsby-and-faunadb/), but there are additional complications involved when allowing users to write whatever they want and post it to your back-end.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +When you expose an input you're giving the reader the opportunity to write anything they like and it's only a matter of time before a tinker writes something rude. Naturally you don't want your blog
```suggestion
When you expose an input, you're giving the reader the opportunity to write _anything_ — it's only a matter of time before someone writes something rude. You probably don't want your blog posts peppered with expletives, so you need to add moderation so an admin needs to approve or delete comments **before** they appear on your blog.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +Aside from the extra technical overhead involved in setting up an Admin user and a moderation queue you'll also need to periodically login, review comments left by readers and then either approve or
```suggestion
In addition to extra technical overhead, setting up a moderation queue also means you have to periodically log in, review comments left by readers, and approve or delete them.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +When i started to think about reactions i was struggling to think of a fun and original way to present the options to the reader. I toyed around with the "heart", "thumbs up" / "thumbs down" approach
```suggestion
When I started to think about reactions I was struggling to think of a fun and original way to present the options to the reader. I toyed around with the "heart", "thumbs up" / "thumbs down" approach for a while but wasn't really excited by it, until I saw [this tweet](https://twitter.com/ChrisGannon/status/1261209022662918144) by [Chris Gannon](https://twitter.com/ChrisGannon).
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +As soon as i saw Chris's Svg Bubble Slider i thought it would make a perfect way to expose a pre-defined set of reactions to allow readers to leave their reactions on a blog post.
```suggestion
As soon as I saw Chris's SVG Bubble Slider, I knew it would make a perfect way to expose a pre-defined set of reactions to allow readers to leave their reactions on a blog post.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +I explained the idea to Chris and he was on board... so long as you don't use this open-source project for financial gain you're free to use it on your blog.
```suggestion
I explained the idea to Chris and he was on board. However this can _only_ be used on free projects. If you want to use it for a commercial project, you’ll need to talk to Chris about a license.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +This post will broadly explain the steps required to add [react-svg-bubble-slider](https://react-svg-bubble-slider.netlify.app/) to a Gatsby blog but you could similarly add this to any React applica
```suggestion
This post will broadly explain the steps required to add [react-svg-bubble-slider](https://react-svg-bubble-slider.netlify.app/) to a Gatsby blog, but you could similarly add this to any React application.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +To get started install the package via `npm` or `yarn`
```suggestion
To get started, install the package via `npm` (or `yarn`).
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +You'll then need to locate your "posts" layout. In a Gatsby project this is typically saved in `src/layouts/post-layout` but in short you'll need to import `SvgBubbleSlider` to the template or layout
```suggestion
You'll then need to locate your "posts" layout. In a Gatsby project this is typically saved in `src/layouts/post-layout`, but in short you'll need to import `SvgBubbleSlider` to the template or layout responsible for handling your posts.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +Once you've decided which layout you'll be amending import `SvgBubbleSlider` and add it to the render method.
```suggestion
Once you've decided which layout you'll be amending, import `SvgBubbleSlider` and add it to the component’s returned JSX.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +By default `SvgBubbleSlider` displays 14 reactions. This is because i wanted to honour Chris Gannon's original [Svg Bubble Slider](https://codepen.io/chrisgannon/pen/GZNgLw/) but in reality you'll li
switched to American spelling for consistency.
```suggestion
By default `SvgBubbleSlider` displays 14 reactions. This is because I wanted to honor Chris Gannon's original [SVG Bubble Slider](https://codepen.io/chrisgannon/pen/GZNgLw/), but in reality you'll want to use a restricted set of reactions.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +There's a couple of "snags" to look out for when using the `icons` prop. Firstly you'll need at least three icons, this is to ensure there's icons to "slide" to and from, and secondly the icon names
```suggestion
There are a couple caveats when using the `icons` prop:

1. You'll need at least three icons. This is to ensure there are icons to "slide" to and from.
2. The icon names must be from the 14 icons included in the package. Check the [docs](https://react-svg-bubble-slider.netlify.app/?path=/docs/icons--page) for available icon names.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +Now that you've got the icons configured you'll need to get the current reaction, show the reader the current reaction and then provide a way for the reader to post the current reaction to your back-
```suggestion
Now that you've got the icons configured, you'll need to get the current reaction, show the reader the current reaction, and then provide a way for the reader to post the current reaction to your back-end of choice.
```

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +            <SvgIcon name={name} />
Where does this come from? Does it need to be imported?

2020-07-10 03:34 UTC, jlengstorf commented on src/posts/2020/06/netlify-reactions.mdx
> +            <SvgIcon name={name} />
also, maybe use a diff here, because it's hard to tell what changed

2020-07-14 01:30 UTC, jlengstorf commented
looking good! the WIP is here with a few more edits. I still need feedback from the team, but let me know if there's anything you see here that you'd like to change https://deploy-preview-3274--www.netlify.app/blog/2020/07/15/add-playful-animated-svg-reactions-to-a-gatsby-blog/

2020-07-14 07:19 UTC, PaulieScanlon commented
Arw Jason, it’s absolutely brills! Thanks for the edits, I do struggle a
bit to get what’s in my head out In words and you’ve made this read so much
better! Thanks for your efforts!

No amends from me, feel free to change anything the team come back with!


Mega thanks mate, I’m really happy with this!

Looking forward to it going live!!

Thanks again!

Paul

On Tue, 14 Jul 2020 at 02:31, Jason Lengstorf <notifications@github.com>
wrote:

> looking good! the WIP is here with a few more edits. I still need feedback
> from the team, but let me know if there's anything you see here that you'd
> like to change
> https://deploy-preview-3274--www.netlify.app/blog/2020/07/15/add-playful-animated-svg-reactions-to-a-gatsby-blog/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PaulieScanlon/paulie-dev-2019/pull/2#issuecomment-657913888>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALF22WP6F2CBHJ622VYKQ3R3OYNZANCNFSM4OWAISNA>
> .
>

2020-07-16 15:24 UTC, closed without merging